/* Generated By:JavaCC: Do not edit this line. SourceParserConstants.java */
package com.iconmaster.srcplugin.lexerjj;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SourceParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int COMMENT = 2;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 3;
  /** RegularExpression Id. */
  int DIRECTIVE = 4;
  /** RegularExpression Id. */
  int KEYWORD = 5;
  /** RegularExpression Id. */
  int WORD = 6;
  /** RegularExpression Id. */
  int WORD_B = 7;
  /** RegularExpression Id. */
  int WORD_E = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int CHAR = 11;
  /** RegularExpression Id. */
  int SYMBOL = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<COMMENT>",
    "<BLOCK_COMMENT>",
    "<DIRECTIVE>",
    "<KEYWORD>",
    "<WORD>",
    "<WORD_B>",
    "<WORD_E>",
    "<NUMBER>",
    "<STRING>",
    "<CHAR>",
    "<SYMBOL>",
  };

}
